### ISSUE TITLE
Runtime error - backend

### ISSUE THREAD

**Issue by victor-yacovlev** [mipt-proglang-2015/proglangs_biktimirov#2]
При подключении браузером по адресу `http://localhost:10000`:

```
./main
2015/12/14 15:34:31 http: panic serving [::1]:36216: runtime error: index out of range
goroutine 5 [running]:
net/http.func·011()
        /usr/lib64/go/src/net/http/server.go:1130 +0xbb
main.func·001(0x7f6362c1a120, 0xc2080561e0, 0xc2080320d0)
        /home/victor/Work/MIPT/6course-2015/aidar.biktimirov/proglangs_biktimirov/backend/src/github.com/aidarbiktimirov/tictactoe/tictactoe_server/main.go:14 +0x487
net/http.HandlerFunc.ServeHTTP(0xc20801e240, 0x7f6362c1a120, 0xc2080561e0, 0xc2080320d0)
        /usr/lib64/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc20803aae0, 0x7f6362c1a120, 0xc2080561e0, 0xc2080320d0)
        /usr/lib64/go/src/net/http/server.go:1541 +0x17d
net/http.serverHandler.ServeHTTP(0xc208054060, 0x7f6362c1a120, 0xc2080561e0, 0xc2080320d0)
        /usr/lib64/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208056000)
        /usr/lib64/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/lib64/go/src/net/http/server.go:1751 +0x35e

```

**Comment by aidarbiktimirov** [comment]
При запуске нужно передавать в качестве входного параметра путь до директории с собранным проектом фронтэнда, добавлю в описание

**Comment by victor-yacovlev** [comment]
Что не совсем корректно.

Сервер должен сам вычислить абсолютный путь (относительно себя-бинарника) к файлам ресурсов.
